# Generated by Django 5.2 on 2025-11-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorieconsumed',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
