# Generated by Django 5.2 on 2025-11-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
