# Generated by Django 5.2 on 2025-11-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0002_alter_calorieconsumed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorieconsumed',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calorieconsumed',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
