# Generated by Django 5.2 on 2025-11-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0003_alter_calorieconsumed_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calorieconsumed',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='calorieconsumed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calorieconsumed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
